Update patch set 1
Patch Set 1: Verified-1

This is an automated message from the Deckard Autoverifier.

Patchset merges but does not build in AOSP.
The following snippet of `make` output may point you in the right direction:

  packages/apps/Mms/src/com/android/mms/ui/ComposeMessageActivity.java:91: cannot find symbol
symbol  : class SubscriptionController
location: package android.telephony
import android.telephony.SubscriptionController;
                        ^
packages/apps/Mms/src/com/android/mms/ui/ComposeMessageActivity.java:92: package android.telephony.SubscriptionController does not exist
import android.telephony.SubscriptionController.SubInfoRecord;
                                               ^
packages/apps/Mms/src/com/android/mms/ui/MessageUtils.java:47: cannot find symbol
...


If your patchset has a dependency in a separate project, please ensure that
both changes are uploaded with the same Change-Id.

Patch-set: 1
Label: Verified=-1