Update patch set 1
Patch Set 1: Fails

This is an automated message from the Deckard Autoverifier.

Patchset creates breakage in Google's internal tree.

Patchset creates breakage in AOSP.
  The following snippet of `make` output may point you in the right direction:
build/core/base_rules.mk:513: dalvik/dx/junit-tests/Android.mk: Module "dx-tests" has useless module tags: tests. It will be installed anyway.
build/core/base_rules.mk:513: libcore/Android.mk: Module "core-tests-hostdex" has useless module tags: tests. It will be installed anyway.
find: `src': No such file or directory
packages/apps/Mms/src/com/android/mms/transaction/TransactionBundle.java:22: cannot find symbol
symbol  : class IccUtils
location: package com.android.internal.telephony.uicc
import com.android.internal.telephony.uicc.IccUtils;
                                          ^
packages/apps/Mms/src/com/android/mms/transaction/TransactionBundle.java:153: cannot find symbol
...

If your patchset has a dependency in a separate project and you believe that this is the cause of the breakage, a reviewer can verify +1 and Deckard will remove the verify -1 shortly thereafter.

Patch-set: 1
Label: Code-Review=0
Label: Verified=-1